In [ ]:
import numpy as np

## Dizi oluşturma fonksiyonları

In [ ]:
print(f"Aralık ile array tanımla: \n {np.arange(0,10,2)}") #ilk eleman dahil, son eleman dahil değil

Aralık ile array tanımla: 
 [0 2 4 6 8]


In [ ]:
print(f"Eşit aralıklar ile array: \n {np.linspace(0,9,6)}") #ilk ve son eleman dahil

Eşit aralıklar ile array: 
 [0.  1.8 3.6 5.4 7.2 9. ]


In [ ]:
print(f"full: \n {np.full((2,4),7)}")

full: 
 [[7 7 7 7]
 [7 7 7 7]]


In [ ]:
print(f"logspace: \n {np.logspace(0,3,4)}") #10^0 ile 10^3 arasında logaritmik aralık 4 sayı oluştur

logspace: 
 [   1.   10.  100. 1000.]


In [ ]:
print(f"birim matris oluşturucu: \n {np.eye(3)}")

birim matris 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
print(f"birim matris olutşru: \n {np.identity(4)}")

birim matris olutşru: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
print(f"empty: \n {np.empty((2,3))}")

empty 
 [[   1.            3.98107171   15.84893192]
 [  63.09573445  251.18864315 1000.        ]]


In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
empty_like_arr = np.empty_like(arr)
print(f"empty_like: \n {empty_like_arr}")

empty_like: 
 [[4607182418800017408 4616146995324808671 4625111773543495782]
 [4634076752501648376 4643041931249352531 4652007308841189376]]


In [ ]:
print(f"tile: \n {np.tile(([1,2,3]),2)}")
print(f"repeat: \n {np.repeat(([1,2,3]),2)}")

tile: 
 [1 2 3 1 2 3]
repeat: 
 [1 1 2 2 3 3]


## İndeksleme ve Dilimleme

In [ ]:
arr = np.array([10,20,30,40,50])

fancy = arr[[0,2,4]]
print(f"fancy: \n {fancy}")


fancy: 
 [10 30 50]


In [ ]:
arr2 = np.array([[10,20],[30,40],[50,60]])
rows = [0,2]
cols = [0]
print(f"seçilen: {arr2[rows,cols]}")

seçilen: [10 50]


In [ ]:
arr = np.array([5,10,15,20,25])
bool_index = arr[arr > 15]
print(f"bool_index: {bool_index}")

bool_index: [20 25]


# View vs Copy

In [ ]:
arr = np.array([10,20,30,40,50])
arr

array([10, 20, 30, 40, 50])

In [ ]:
slice_view = arr[1:4]
slice_view[:] = 0
print(arr)

[10  0  0  0 50]


In [ ]:
arr2 = np.array([10,20,30,40,50])
arr2

array([10, 20, 30, 40, 50])

In [ ]:
slice_copy = arr2[1:4].copy()
slice_copy[:] = 0
print(arr2)
slice_copy

[10 20 30 40 50]


array([0, 0, 0])

#Dizi İşlemleri

In [ ]:
arr = np.array([1,2,3,4,5])
print(f"min değerin indeksi {np.argmin(arr)}")
print(f"max değerin indeksi {np.argmax(arr)}")

min değerin indeksi 0
max değerin indeksi 4


In [ ]:
arr = np.array([1,2,3,4,5])
print(f"Kümülatif toplam:  {np.cumsum(arr)}")
print(f"Kümülatif çarpım: {np.cumprod(arr)}")

Kümülatif toplam:  [ 1  3  6 10 15]
Kümülatif çarpım: [  1   2   6  24 120]


## Şekil İşlemleri

In [ ]:
arr = np.arange(12)
print(arr)
reshaped = arr.reshape(3,4)
print(reshaped)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
from re import A
arr = np.array([[1,2,3],[4,5,6]])
arr
print(f"ravel: {np.ravel(arr)}") #view döner
print(f"flatten: {arr.flatten()}") #copy döner


ravel: [1 2 3 4 5 6]
flatten: [1 2 3 4 5 6]


In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
arr
print(f"transpose: {arr.transpose()}")

transpose: [[1 4]
 [2 5]
 [3 6]]


In [ ]:
arr = np.array([1,2,3])
print(arr.shape)
expanded = np.expand_dims(arr,axis=0) # satır ekle
print(expanded.shape)
squeezed = np.squeeze(expanded)
print(squeezed.shape)

(3,)
(1, 3)
(3,)


In [ ]:
#genel birleştirme
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])

concat = np.concatenate((a,b),axis=0)
print(concat)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
#dikey birleştirme
vstacked = np.vstack((a,b))
vstacked

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
#yatay birleştirme
hstacked = np.hstack((a,np.array([[7,8],[9,10]])))
hstacked

array([[ 1,  2,  7,  8],
       [ 3,  4,  9, 10]])

## dizileri ayırma

In [ ]:
arr = np.arange(10)
print(f"split:{np.split(arr,5)}") #5 eşit parçaya ayır

split:[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]


In [ ]:
print(f"split:{np.array_split(arr,4)}") #4 parçaya ayır

split:[array([0, 1, 2]), array([3, 4, 5]), array([6, 7]), array([8, 9])]


## Rastgele Sayılar

In [ ]:
#0-1 arasında rastgele sayı üret (uniform dağılım)
print(f"rand: \n {np.random.rand(3,3)}")

# normal dağılıma göre rastgele sayı üret
print(f"randn: \n {np.random.randn(3,3)}")

# belirli bir aralıkta rastgele sayı üret
print(f"randint: \n {np.random.randint(1,10,(3,3))}")

rand: 
 [[0.64057316 0.56805088 0.21994167]
 [0.18726843 0.88865027 0.92420335]
 [0.77663231 0.38956898 0.67914133]]
randn: 
 [[ 0.31122187 -0.88596607  1.898714  ]
 [ 0.97659984  0.68416649 -0.85618005]
 [ 1.19964308  0.18796973 -0.81807199]]
randint: 
 [[4 7 7]
 [1 2 6]
 [4 3 6]]


In [ ]:
#belirli kümeden rastgele seçmek
arr = np.array([1,2,3,4,5])
print(f"tek seçim: \n {np.random.choice(arr)}")
print(f"çoklu seçim: \n {np.random.choice(arr,size=3,replace=False)}") # replace fonksiyonu aynı karakter seçip seçmediğini belirler

tek seçim: 
 3
çoklu seçim: 
 [5 4 2]


In [ ]:
#permütasyon ve shuffle
arr = np.array([1,2,3,4,5])
print(f"permütasyon: \n {np.random.permutation(arr)}") #yeni dizi döndürür
np.random.shuffle(arr) #diziyi yerinde karıştırır
print(f"shuffle: \n {arr}")

permütasyon: 
 [3 2 5 1 4]
shuffle: 
 [4 5 1 2 3]


In [ ]:
#olasılık dağılımları
binom = np.random.binomial(n=10,p=0.5,size=5)
print(binom)
poisson = np.random.poisson(lam=5,size=5)
print(poisson)
normal = np.random.normal(loc=0,scale=1,size=5)
print(normal)
uniform = np.random.uniform(0,1,5)
print(uniform)

[6 3 5 5 4]
[6 5 4 4 4]
[-2.09159967  1.26374053 -0.01548334 -0.02737645  0.81787351]
[0.71227059 0.14808693 0.99774049 0.26678101 0.97661496]


In [ ]:
#Seed: rastgele sayıların tekrarlanabilir olmasını sağlar.
np.random.seed(42) #bundan sonraki rastgelelikler her çalıştığında farklı değer döndürmez
np.random.randint(0,10,15)

array([6, 3, 7, 4, 6, 9, 2, 6, 7, 4, 3, 7, 7, 2, 5])

## İstatistik ve Veri Analizi

In [ ]:
data = np.array([12,1,23,31,123,4,1])
from scipy import stats
print(f"mod: {stats.mode(data,keepdims=True).mode[0]}")
print(f"ortalama: {np.mean(data)}")
print(f"medyan: {np.median(data)}")
print(f"varyans: {np.var(data)}")
print(f"standart sapma: {np.std(data)}")

mod: 1
ortalama: 27.857142857142858
medyan: 12.0
varyans: 1621.265306122449
korelasyon: 1.0
standart sapma: 40.264938918647935


In [ ]:
print(f"25.percentil: {np.percentile(data,25)}")
print(f"75.percentil: {np.percentile(data,75)}")

print(f"0.25.percentil: {np.quantile(data,0.25)}")
print(f"0.75.percentil: {np.quantile(data,0.75)}")

25.percentil: 2.5
75.percentil: 27.0
0.25.percentil: 2.5
0.75.percentil: 27.0


In [ ]:
#korelasyon ve kovaryans

x = np.array([1,2,3,4,5])
y = np.array([2,4,6,8,10])

print(f"korelasyon: \n{np.corrcoef(x,y)}")
print(f"kovaryans: \n{np.cov(x,y)}")

korelasyon: 
[[1. 1.]
 [1. 1.]]
kovaryans: 
[[ 2.5  5. ]
 [ 5.  10. ]]


## Lineer Cebir

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(f"dot: {np.dot(a,b)}")
print(f"vdot: {np.vdot(a,b)}")

dot: 32
vdot: 32


In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(f"matmul: \n {np.matmul(a,b)}")


matmul: 
 [[19 22]
 [43 50]]


In [ ]:
a = np.array([[1,2],[3,4]])
det = np.linalg.det(a)
det

np.float64(-2.0000000000000004)

In [ ]:
a = np.array([[1,2],[3,4]])
inv_a = np.linalg.inv(a)
inv_a

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
a = np.array([[1,2],[3,4]])
print(f"rank: {np.linalg.matrix_rank(a)}")

rank: 2


In [ ]:
a = np.array([[1,2],[3,4]])
eigenvalues, eigenvectors = np.linalg.eig(a)
print(f"eigenvalues: {eigenvalues}")
print(f"eigenvectors: {eigenvectors}")


eigenvalues: [-0.37228132  5.37228132]
eigenvectors: [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [ ]:
#lineer denklem çözümü
"""
2x+y=5
x-y=1
"""
a = np.array([[2,1],[1,-1]])
b = np.array([5,1])
solution = np.linalg.solve(a,b)
solution

array([2., 1.])

## Maskeler ve Koşullu İşlemler

In [ ]:
# boolean diziler

arr = np.array([10,20,30,40,50])
mask = arr > 25
print(mask)
print(arr[mask])

[False False  True  True  True]
[30 40 50]


In [ ]:
#where komutuna göre seçim
arr = np.array([10,20,30,40,50])

result = np.where(arr < 25,0,arr)
result

array([ 0,  0, 30, 40, 50])

In [ ]:
arr = np.array([10,20,30,40,50])

conditions = [arr < 20, arr < 40, arr >= 40]
choices = ["küçük","orta","büyük"]

labels = np.select(conditions,choices,default="bilinmiyor")
labels

array(['küçük', 'orta', 'orta', 'büyük', 'büyük'], dtype='<U10')

In [ ]:
#non zero
arr = np.array([10,20,30,40,50])
print(np.nonzero(arr)) #0 olmayanların indeksini döndürüyor

(array([0, 1, 2, 3, 4]),)


In [ ]:
# any ve all
arr = np.array([10,20,30,40,50])
print(f"Herhangi biri 30dan büyük mü {np.any(arr > 30)}")
print(f"Tüm değerler 30dan büyük mü {np.all(arr > 30)}")

Herhangi biri 30dan büyük mü True
Tüm değerler 30dan büyük mü False


## Dosya işlemleri

In [ ]:
arr = np.array([10,20,30,40,50])
np.save("data.npy",arr)
loaded_arr=np.load("data.npy")
loaded_arr

array([10, 20, 30, 40, 50])